
	INCLUDE	"hardware.inc"
	INCLUDE "header.inc"

;--------------------------------------------------------------------------

	SECTION	"VAR",BSS

int_repetition:	DS	1
	
	SECTION	"Main",HOME

;--------------------------------------------------------------------------
;- Main()                                                                 -
;--------------------------------------------------------------------------

Main:

	; -------------------------------------------------------
	
	ld	a,$0A
	ld	[$0000],a ; enable ram
	
	ld	hl,$A000
	
	; -------------------------------------------------------

PERFORM_TEST_HALT : MACRO
	di
	
	push	hl
	
	xor	a,a
	ld	[int_repetition],a
	
	ld	bc,$0200
	ld	hl,\1
	ld	de,$D000
	call	memcopy
	
	ld	a,TACF_START|TACF_262KHZ
	ld	[rTAC],a
	
	xor	a,a
	ld	c,rDIV & $FF
	ld	hl,rTIMA
	ld	a,$F0
	ld	[rTMA],a
	ld	[$FF00+c],a
	ld	[hl],a
	ld	[$FF00+c],a
	ld	[hl],a

	ld	a,IEF_TIMER
	ld	[rIE],a
	
	xor	a,a
	ld	[rIF],a
	
	pop	hl
	
	ei

	halt
ENDM

PERFORM_TEST_NO_HALT : MACRO
	di
	
	push	hl
	
	xor	a,a
	ld	[int_repetition],a
	
	ld	bc,$0200
	ld	hl,\1
	ld	de,$D000
	call	memcopy
	
	ld	a,TACF_START|TACF_262KHZ
	ld	[rTAC],a
	
	xor	a,a
	ld	c,rDIV & $FF
	ld	hl,rTIMA
	ld	a,$F0
	ld	[rTMA],a
	ld	[$FF00+c],a
	ld	[hl],a
	ld	[$FF00+c],a
	ld	[hl],a

	ld	a,IEF_TIMER
	ld	[rIE],a
	
	xor	a,a
	ld	[rIF],a
	
	pop	hl
	
	ei

	REPT 50
	nop
	ENDR
ENDM

	ld	a,$80
	ld	[rNR52],a
	ld	a,$FF
	ld	[rNR51],a
	ld	a,$77
	ld	[rNR50],a
	
	ld	a,$C0
	ld	[rNR11],a
	ld	a,$E0
	ld	[rNR12],a
	ld	a,$00
	ld	[rNR13],a
	ld	a,$82
	ld	[rNR14],a

	PERFORM_TEST_HALT TIMER_INT_HANDLER_0
	PERFORM_TEST_HALT TIMER_INT_HANDLER_1
	PERFORM_TEST_HALT TIMER_INT_HANDLER_2
	PERFORM_TEST_HALT TIMER_INT_HANDLER_3
	PERFORM_TEST_HALT TIMER_INT_HANDLER_4
	PERFORM_TEST_HALT TIMER_INT_HANDLER_5
	PERFORM_TEST_HALT TIMER_INT_HANDLER_6
	PERFORM_TEST_HALT TIMER_INT_HANDLER_7
	PERFORM_TEST_HALT TIMER_INT_HANDLER_8
	PERFORM_TEST_HALT TIMER_INT_HANDLER_9
	PERFORM_TEST_HALT TIMER_INT_HANDLER_10
	PERFORM_TEST_HALT TIMER_INT_HANDLER_11
	PERFORM_TEST_HALT TIMER_INT_HANDLER_12
	PERFORM_TEST_HALT TIMER_INT_HANDLER_13
	PERFORM_TEST_HALT TIMER_INT_HANDLER_14
	PERFORM_TEST_HALT TIMER_INT_HANDLER_15
	PERFORM_TEST_HALT TIMER_INT_HANDLER_16
	PERFORM_TEST_HALT TIMER_INT_HANDLER_17
	PERFORM_TEST_HALT TIMER_INT_HANDLER_18
	PERFORM_TEST_HALT TIMER_INT_HANDLER_19
	PERFORM_TEST_HALT TIMER_INT_HANDLER_20
	PERFORM_TEST_HALT TIMER_INT_HANDLER_21
	PERFORM_TEST_HALT TIMER_INT_HANDLER_22
	PERFORM_TEST_HALT TIMER_INT_HANDLER_23
	PERFORM_TEST_HALT TIMER_INT_HANDLER_24
	PERFORM_TEST_HALT TIMER_INT_HANDLER_25
	PERFORM_TEST_HALT TIMER_INT_HANDLER_26
	PERFORM_TEST_HALT TIMER_INT_HANDLER_27
	PERFORM_TEST_HALT TIMER_INT_HANDLER_28
	PERFORM_TEST_HALT TIMER_INT_HANDLER_29
	PERFORM_TEST_HALT TIMER_INT_HANDLER_30
	PERFORM_TEST_HALT TIMER_INT_HANDLER_31
	
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_0
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_1
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_2
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_3
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_4
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_5
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_6
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_7
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_8
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_9
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_10
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_11
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_12
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_13
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_14
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_15
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_16
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_17
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_18
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_19
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_20
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_21
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_22
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_23
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_24
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_25
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_26
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_27
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_28
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_29
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_30
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_31
	
	ld	a,$00
	ld	[$0000],a ; disable ram
	
	call	CPU_fast
	
	ld	a,$0A
	ld	[$0000],a ; enable ram
	
	ld	a,$80
	ld	[rNR52],a
	ld	a,$FF
	ld	[rNR51],a
	ld	a,$77
	ld	[rNR50],a
	
	ld	a,$C0
	ld	[rNR11],a
	ld	a,$E0
	ld	[rNR12],a
	ld	a,$00
	ld	[rNR13],a
	ld	a,$81
	ld	[rNR14],a

	PERFORM_TEST_HALT TIMER_INT_HANDLER_0
	PERFORM_TEST_HALT TIMER_INT_HANDLER_1
	PERFORM_TEST_HALT TIMER_INT_HANDLER_2
	PERFORM_TEST_HALT TIMER_INT_HANDLER_3
	PERFORM_TEST_HALT TIMER_INT_HANDLER_4
	PERFORM_TEST_HALT TIMER_INT_HANDLER_5
	PERFORM_TEST_HALT TIMER_INT_HANDLER_6
	PERFORM_TEST_HALT TIMER_INT_HANDLER_7
	PERFORM_TEST_HALT TIMER_INT_HANDLER_8
	PERFORM_TEST_HALT TIMER_INT_HANDLER_9
	PERFORM_TEST_HALT TIMER_INT_HANDLER_10
	PERFORM_TEST_HALT TIMER_INT_HANDLER_11
	PERFORM_TEST_HALT TIMER_INT_HANDLER_12
	PERFORM_TEST_HALT TIMER_INT_HANDLER_13
	PERFORM_TEST_HALT TIMER_INT_HANDLER_14
	PERFORM_TEST_HALT TIMER_INT_HANDLER_15
	PERFORM_TEST_HALT TIMER_INT_HANDLER_16
	PERFORM_TEST_HALT TIMER_INT_HANDLER_17
	PERFORM_TEST_HALT TIMER_INT_HANDLER_18
	PERFORM_TEST_HALT TIMER_INT_HANDLER_19
	PERFORM_TEST_HALT TIMER_INT_HANDLER_20
	PERFORM_TEST_HALT TIMER_INT_HANDLER_21
	PERFORM_TEST_HALT TIMER_INT_HANDLER_22
	PERFORM_TEST_HALT TIMER_INT_HANDLER_23
	PERFORM_TEST_HALT TIMER_INT_HANDLER_24
	PERFORM_TEST_HALT TIMER_INT_HANDLER_25
	PERFORM_TEST_HALT TIMER_INT_HANDLER_26
	PERFORM_TEST_HALT TIMER_INT_HANDLER_27
	PERFORM_TEST_HALT TIMER_INT_HANDLER_28
	PERFORM_TEST_HALT TIMER_INT_HANDLER_29
	PERFORM_TEST_HALT TIMER_INT_HANDLER_30
	PERFORM_TEST_HALT TIMER_INT_HANDLER_31
	
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_0
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_1
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_2
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_3
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_4
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_5
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_6
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_7
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_8
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_9
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_10
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_11
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_12
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_13
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_14
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_15
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_16
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_17
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_18
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_19
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_20
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_21
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_22
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_23
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_24
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_25
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_26
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_27
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_28
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_29
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_30
	PERFORM_TEST_NO_HALT TIMER_INT_HANDLER_31

	; -------------------------------------------------------
	
	ld	a,$80
	ld	[rNR52],a
	ld	a,$FF
	ld	[rNR51],a
	ld	a,$77
	ld	[rNR50],a
	
	ld	a,$C0
	ld	[rNR11],a
	ld	a,$E0
	ld	[rNR12],a
	ld	a,$00
	ld	[rNR13],a
	ld	a,$87
	ld	[rNR14],a
	
	push	hl
	ld	[hl],$12
	inc hl
	ld	[hl],$34
	inc hl
	ld	[hl],$56
	inc hl
	ld	[hl],$78
	pop	hl
	
	ld	a,$00
	ld	[$0000],a ; disable ram

.endloop:
	halt
	jr	.endloop

; --------------------------------------------------------------

	SECTION "functions",ROMX,BANK[1]
	
TIMER_INT_HANDLER_MACRO : MACRO
	ld	a,[int_repetition]
	cp	a,1
	jr	z,.is_1\@
	
	ld	a,1
	ld	[int_repetition],a
	
	push	de
	pop		de
	push	de
	pop		de ; delay
	
	
	ld	b,0
	
	ei
	
	REPT	\1
	inc	b
	ENDR
	
	di
	
	ret
	
.is_1\@:
	ld	a,b
	ld	[hl+],a
	ld	a,[rTIMA]
	ld	[hl+],a
	nop
	ld	a,[rTIMA]
	ld	[hl+],a
	nop
	ld	a,[rTIMA]
	ld	[hl+],a
	nop
	ld	a,[rTIMA]
	ld	[hl+],a
	nop

	ret
ENDM

TIMER_INT_HANDLER_0: TIMER_INT_HANDLER_MACRO 0
TIMER_INT_HANDLER_1: TIMER_INT_HANDLER_MACRO 1
TIMER_INT_HANDLER_2: TIMER_INT_HANDLER_MACRO 2
TIMER_INT_HANDLER_3: TIMER_INT_HANDLER_MACRO 3
TIMER_INT_HANDLER_4: TIMER_INT_HANDLER_MACRO 4
TIMER_INT_HANDLER_5: TIMER_INT_HANDLER_MACRO 5
TIMER_INT_HANDLER_6: TIMER_INT_HANDLER_MACRO 6
TIMER_INT_HANDLER_7: TIMER_INT_HANDLER_MACRO 7
TIMER_INT_HANDLER_8: TIMER_INT_HANDLER_MACRO 8
TIMER_INT_HANDLER_9: TIMER_INT_HANDLER_MACRO 9
TIMER_INT_HANDLER_10: TIMER_INT_HANDLER_MACRO 10
TIMER_INT_HANDLER_11: TIMER_INT_HANDLER_MACRO 11
TIMER_INT_HANDLER_12: TIMER_INT_HANDLER_MACRO 12
TIMER_INT_HANDLER_13: TIMER_INT_HANDLER_MACRO 13
TIMER_INT_HANDLER_14: TIMER_INT_HANDLER_MACRO 14
TIMER_INT_HANDLER_15: TIMER_INT_HANDLER_MACRO 15
TIMER_INT_HANDLER_16: TIMER_INT_HANDLER_MACRO 16
TIMER_INT_HANDLER_17: TIMER_INT_HANDLER_MACRO 17
TIMER_INT_HANDLER_18: TIMER_INT_HANDLER_MACRO 18
TIMER_INT_HANDLER_19: TIMER_INT_HANDLER_MACRO 19
TIMER_INT_HANDLER_20: TIMER_INT_HANDLER_MACRO 20
TIMER_INT_HANDLER_21: TIMER_INT_HANDLER_MACRO 21
TIMER_INT_HANDLER_22: TIMER_INT_HANDLER_MACRO 22
TIMER_INT_HANDLER_23: TIMER_INT_HANDLER_MACRO 23
TIMER_INT_HANDLER_24: TIMER_INT_HANDLER_MACRO 24
TIMER_INT_HANDLER_25: TIMER_INT_HANDLER_MACRO 25
TIMER_INT_HANDLER_26: TIMER_INT_HANDLER_MACRO 26
TIMER_INT_HANDLER_27: TIMER_INT_HANDLER_MACRO 27
TIMER_INT_HANDLER_28: TIMER_INT_HANDLER_MACRO 28
TIMER_INT_HANDLER_29: TIMER_INT_HANDLER_MACRO 29
TIMER_INT_HANDLER_30: TIMER_INT_HANDLER_MACRO 30
TIMER_INT_HANDLER_31: TIMER_INT_HANDLER_MACRO 31

; --------------------------------------------------------------

