
	INCLUDE	"hardware.inc"
	INCLUDE "header.inc"

	
	SECTION	"var",BSS
	
repeat_loop:	DS 1

	SECTION	"Main",HOME
	
;--------------------------------------------------------------------------
;- Main()                                                                 -
;--------------------------------------------------------------------------

Main:
	
	ld	a,0
	ld	hl,$FE00
.filloam:
	ld	[hl+],a
	inc	a
	cp	a,$A0
	jr	nz,.filloam
	
	; -------------------------------------------------------
	
	ld	a,$0A
	ld	[$0000],a ; enable ram
	
	ld	hl,$A000
	
	ld	a,LCDCF_ON|LCDCF_OBJON
	ld	[rLCDC],a
	
	ld	a,[Init_Reg_A]
	cp	a,$11
	jr	nz,.skip1
	ld	a,0
	ld	[repeat_loop],a
	call	CPU_slow
.skip1:

.repeat_all:
	
	; -------------------------------------------------------

PERFORM_TEST : MACRO
	di
	
	push	hl
	
	ld	bc,$007F
	ld	hl,\1
	ld	de,$FF80
	call	memcopy
	
	ld	b,45
	call	wait_ly
	
	ld	a,50
	ld	[rLYC],a
	ld	a,STATF_LYC
	ld	[rSTAT],a
	
	ld	a,IEF_LCDC
	ld	[rIE],a
	
	xor	a,a
	ld	[rIF],a
	
	pop	hl
	
	ei

	halt
ENDM


	PERFORM_TEST LCD_INT_HANDLER_0
	PERFORM_TEST LCD_INT_HANDLER_1
	PERFORM_TEST LCD_INT_HANDLER_2
	PERFORM_TEST LCD_INT_HANDLER_3
	PERFORM_TEST LCD_INT_HANDLER_4
	PERFORM_TEST LCD_INT_HANDLER_5
	PERFORM_TEST LCD_INT_HANDLER_6
	PERFORM_TEST LCD_INT_HANDLER_7
	PERFORM_TEST LCD_INT_HANDLER_8
	PERFORM_TEST LCD_INT_HANDLER_9
	PERFORM_TEST LCD_INT_HANDLER_10
	PERFORM_TEST LCD_INT_HANDLER_11
	PERFORM_TEST LCD_INT_HANDLER_12
	PERFORM_TEST LCD_INT_HANDLER_13
	PERFORM_TEST LCD_INT_HANDLER_14
	PERFORM_TEST LCD_INT_HANDLER_15
	PERFORM_TEST LCD_INT_HANDLER_16
	PERFORM_TEST LCD_INT_HANDLER_17
	PERFORM_TEST LCD_INT_HANDLER_18
	PERFORM_TEST LCD_INT_HANDLER_19
	PERFORM_TEST LCD_INT_HANDLER_20
	PERFORM_TEST LCD_INT_HANDLER_21
	PERFORM_TEST LCD_INT_HANDLER_22
	PERFORM_TEST LCD_INT_HANDLER_23
	PERFORM_TEST LCD_INT_HANDLER_24
	PERFORM_TEST LCD_INT_HANDLER_25
	PERFORM_TEST LCD_INT_HANDLER_26
	PERFORM_TEST LCD_INT_HANDLER_27
	PERFORM_TEST LCD_INT_HANDLER_28
	PERFORM_TEST LCD_INT_HANDLER_29
	PERFORM_TEST LCD_INT_HANDLER_30
	PERFORM_TEST LCD_INT_HANDLER_31
	PERFORM_TEST LCD_INT_HANDLER_32
	PERFORM_TEST LCD_INT_HANDLER_33
	PERFORM_TEST LCD_INT_HANDLER_34
	PERFORM_TEST LCD_INT_HANDLER_35
	PERFORM_TEST LCD_INT_HANDLER_36
	PERFORM_TEST LCD_INT_HANDLER_37
	PERFORM_TEST LCD_INT_HANDLER_38
	PERFORM_TEST LCD_INT_HANDLER_39
	PERFORM_TEST LCD_INT_HANDLER_40
	PERFORM_TEST LCD_INT_HANDLER_41
	PERFORM_TEST LCD_INT_HANDLER_42
	PERFORM_TEST LCD_INT_HANDLER_43
	PERFORM_TEST LCD_INT_HANDLER_44
	PERFORM_TEST LCD_INT_HANDLER_45
	PERFORM_TEST LCD_INT_HANDLER_46
	PERFORM_TEST LCD_INT_HANDLER_47
	PERFORM_TEST LCD_INT_HANDLER_48
	PERFORM_TEST LCD_INT_HANDLER_49
	PERFORM_TEST LCD_INT_HANDLER_50
	PERFORM_TEST LCD_INT_HANDLER_51
	PERFORM_TEST LCD_INT_HANDLER_52
	PERFORM_TEST LCD_INT_HANDLER_53
	PERFORM_TEST LCD_INT_HANDLER_54
	PERFORM_TEST LCD_INT_HANDLER_55
	PERFORM_TEST LCD_INT_HANDLER_56
	PERFORM_TEST LCD_INT_HANDLER_57
	PERFORM_TEST LCD_INT_HANDLER_58
	PERFORM_TEST LCD_INT_HANDLER_59
	PERFORM_TEST LCD_INT_HANDLER_60
	PERFORM_TEST LCD_INT_HANDLER_61
	PERFORM_TEST LCD_INT_HANDLER_62
	PERFORM_TEST LCD_INT_HANDLER_63


	; -------------------------------------------------------
	
	push	hl
	ld	[hl],$12
	inc hl
	ld	[hl],$34
	inc hl
	ld	[hl],$56
	inc hl
	ld	[hl],$78
	pop	hl
	
	; -------------------------------------------------------
	
	ld	a,[Init_Reg_A]
	cp	a,$11
	jr	nz,.dontchange
	ld	a,[repeat_loop]
	and	a,a
	jr	nz,.dontchange
	; -------------------------------------------------------

	call	CPU_fast
	ld	a,1
	ld	[repeat_loop],a
	jp	.repeat_all
.dontchange:
	
	; -------------------------------------------------------

	ld	a,$00
	ld	[$0000],a ; disable ram
	
	call	screen_off
	
	ld	a,$80
	ld	[rNR52],a
	ld	a,$FF
	ld	[rNR51],a
	ld	a,$77
	ld	[rNR50],a
	
	ld	a,$C0
	ld	[rNR11],a
	ld	a,$E0
	ld	[rNR12],a
	ld	a,$00
	ld	[rNR13],a
	ld	a,$87
	ld	[rNR14],a
	

.endloop:
	halt
	jr	.endloop

; --------------------------------------------------------------

	SECTION "functions",ROMX,BANK[1]
	
LCD_INT_HANDLER_MACRO : MACRO
	REPT \1
	nop
	ENDR
	ld	a,[$FE00]
	ld	[hl+],a
	ret
ENDM

LCD_INT_HANDLER_0: LCD_INT_HANDLER_MACRO 0
LCD_INT_HANDLER_1: LCD_INT_HANDLER_MACRO 1
LCD_INT_HANDLER_2: LCD_INT_HANDLER_MACRO 2
LCD_INT_HANDLER_3: LCD_INT_HANDLER_MACRO 3
LCD_INT_HANDLER_4: LCD_INT_HANDLER_MACRO 4
LCD_INT_HANDLER_5: LCD_INT_HANDLER_MACRO 5
LCD_INT_HANDLER_6: LCD_INT_HANDLER_MACRO 6
LCD_INT_HANDLER_7: LCD_INT_HANDLER_MACRO 7
LCD_INT_HANDLER_8: LCD_INT_HANDLER_MACRO 8
LCD_INT_HANDLER_9: LCD_INT_HANDLER_MACRO 9
LCD_INT_HANDLER_10: LCD_INT_HANDLER_MACRO 10
LCD_INT_HANDLER_11: LCD_INT_HANDLER_MACRO 11
LCD_INT_HANDLER_12: LCD_INT_HANDLER_MACRO 12
LCD_INT_HANDLER_13: LCD_INT_HANDLER_MACRO 13
LCD_INT_HANDLER_14: LCD_INT_HANDLER_MACRO 14
LCD_INT_HANDLER_15: LCD_INT_HANDLER_MACRO 15
LCD_INT_HANDLER_16: LCD_INT_HANDLER_MACRO 16
LCD_INT_HANDLER_17: LCD_INT_HANDLER_MACRO 17
LCD_INT_HANDLER_18: LCD_INT_HANDLER_MACRO 18
LCD_INT_HANDLER_19: LCD_INT_HANDLER_MACRO 19
LCD_INT_HANDLER_20: LCD_INT_HANDLER_MACRO 20
LCD_INT_HANDLER_21: LCD_INT_HANDLER_MACRO 21
LCD_INT_HANDLER_22: LCD_INT_HANDLER_MACRO 22
LCD_INT_HANDLER_23: LCD_INT_HANDLER_MACRO 23
LCD_INT_HANDLER_24: LCD_INT_HANDLER_MACRO 24
LCD_INT_HANDLER_25: LCD_INT_HANDLER_MACRO 25
LCD_INT_HANDLER_26: LCD_INT_HANDLER_MACRO 26
LCD_INT_HANDLER_27: LCD_INT_HANDLER_MACRO 27
LCD_INT_HANDLER_28: LCD_INT_HANDLER_MACRO 28
LCD_INT_HANDLER_29: LCD_INT_HANDLER_MACRO 29
LCD_INT_HANDLER_30: LCD_INT_HANDLER_MACRO 30
LCD_INT_HANDLER_31: LCD_INT_HANDLER_MACRO 31
LCD_INT_HANDLER_32: LCD_INT_HANDLER_MACRO 32
LCD_INT_HANDLER_33: LCD_INT_HANDLER_MACRO 33
LCD_INT_HANDLER_34: LCD_INT_HANDLER_MACRO 34
LCD_INT_HANDLER_35: LCD_INT_HANDLER_MACRO 35
LCD_INT_HANDLER_36: LCD_INT_HANDLER_MACRO 36
LCD_INT_HANDLER_37: LCD_INT_HANDLER_MACRO 37
LCD_INT_HANDLER_38: LCD_INT_HANDLER_MACRO 38
LCD_INT_HANDLER_39: LCD_INT_HANDLER_MACRO 39
LCD_INT_HANDLER_40: LCD_INT_HANDLER_MACRO 40
LCD_INT_HANDLER_41: LCD_INT_HANDLER_MACRO 41
LCD_INT_HANDLER_42: LCD_INT_HANDLER_MACRO 42
LCD_INT_HANDLER_43: LCD_INT_HANDLER_MACRO 43
LCD_INT_HANDLER_44: LCD_INT_HANDLER_MACRO 44
LCD_INT_HANDLER_45: LCD_INT_HANDLER_MACRO 45
LCD_INT_HANDLER_46: LCD_INT_HANDLER_MACRO 46
LCD_INT_HANDLER_47: LCD_INT_HANDLER_MACRO 47
LCD_INT_HANDLER_48: LCD_INT_HANDLER_MACRO 48
LCD_INT_HANDLER_49: LCD_INT_HANDLER_MACRO 49
LCD_INT_HANDLER_50: LCD_INT_HANDLER_MACRO 50
LCD_INT_HANDLER_51: LCD_INT_HANDLER_MACRO 51
LCD_INT_HANDLER_52: LCD_INT_HANDLER_MACRO 52
LCD_INT_HANDLER_53: LCD_INT_HANDLER_MACRO 53
LCD_INT_HANDLER_54: LCD_INT_HANDLER_MACRO 54
LCD_INT_HANDLER_55: LCD_INT_HANDLER_MACRO 55
LCD_INT_HANDLER_56: LCD_INT_HANDLER_MACRO 56
LCD_INT_HANDLER_57: LCD_INT_HANDLER_MACRO 57
LCD_INT_HANDLER_58: LCD_INT_HANDLER_MACRO 58
LCD_INT_HANDLER_59: LCD_INT_HANDLER_MACRO 59
LCD_INT_HANDLER_60: LCD_INT_HANDLER_MACRO 60
LCD_INT_HANDLER_61: LCD_INT_HANDLER_MACRO 61
LCD_INT_HANDLER_62: LCD_INT_HANDLER_MACRO 62
LCD_INT_HANDLER_63: LCD_INT_HANDLER_MACRO 63


; --------------------------------------------------------------

